#pragma once

#include "sdkconfig.h"

#ifndef CONFIG_TFT_SPI_MODE
#define CONFIG_TFT_SPI_MODE 0
#endif
#ifndef CONFIG_TFT_COLOR_ORDER_BGR
#define CONFIG_TFT_COLOR_ORDER_BGR 0
#endif
#ifndef CONFIG_TFT_INVERT_COLOR
#define CONFIG_TFT_INVERT_COLOR 0
#endif
#ifndef CONFIG_TFT_TEST_PATTERN
#define CONFIG_TFT_TEST_PATTERN 1
#endif
#ifndef CONFIG_TFT_I2C_SDA
#define CONFIG_TFT_I2C_SDA 4
#endif
#ifndef CONFIG_TFT_I2C_SCL
#define CONFIG_TFT_I2C_SCL 17
#endif
#ifndef CONFIG_TFT_I2C_FREQ_HZ
#define CONFIG_TFT_I2C_FREQ_HZ 400000
#endif
#ifndef CONFIG_TFT_MCP23017_ADDR
#define CONFIG_TFT_MCP23017_ADDR 0x20
#endif
#ifndef CONFIG_TFT_MCP23017_RST
#define CONFIG_TFT_MCP23017_RST 18
#endif
#ifndef CONFIG_TFT_ENCODER_PIN_A
#define CONFIG_TFT_ENCODER_PIN_A 1
#endif
#ifndef CONFIG_TFT_ENCODER_PIN_B
#define CONFIG_TFT_ENCODER_PIN_B 2
#endif
#ifndef CONFIG_TFT_ENCODER_PIN_SW
#define CONFIG_TFT_ENCODER_PIN_SW 3
#endif
#ifndef CONFIG_TFT_SDMMC_MOUNT_POINT
#define CONFIG_TFT_SDMMC_MOUNT_POINT "/sdcard"
#endif
#ifndef CONFIG_TFT_OTA_BIN_PATH
#define CONFIG_TFT_OTA_BIN_PATH "/sdcard/firmware.bin"
#endif
#ifndef CONFIG_TFT_SDMMC_FREQ_KHZ
#define CONFIG_TFT_SDMMC_FREQ_KHZ 20000
#endif
#ifndef CONFIG_TFT_TOUCH_SPI_MOSI
#define CONFIG_TFT_TOUCH_SPI_MOSI 6
#endif
#ifndef CONFIG_TFT_TOUCH_SPI_MISO
#define CONFIG_TFT_TOUCH_SPI_MISO 5
#endif
#ifndef CONFIG_TFT_TOUCH_SPI_SCLK
#define CONFIG_TFT_TOUCH_SPI_SCLK 7
#endif
#ifndef CONFIG_TFT_TOUCH_X_MIN
#define CONFIG_TFT_TOUCH_X_MIN 200
#endif
#ifndef CONFIG_TFT_TOUCH_X_MAX
#define CONFIG_TFT_TOUCH_X_MAX 3800
#endif
#ifndef CONFIG_TFT_TOUCH_Y_MIN
#define CONFIG_TFT_TOUCH_Y_MIN 200
#endif
#ifndef CONFIG_TFT_TOUCH_Y_MAX
#define CONFIG_TFT_TOUCH_Y_MAX 3800
#endif
#ifndef CONFIG_TFT_TOUCH_SWAP_XY
#define CONFIG_TFT_TOUCH_SWAP_XY 0
#endif
#ifndef CONFIG_TFT_TOUCH_MIRROR_X
#define CONFIG_TFT_TOUCH_MIRROR_X 0
#endif
#ifndef CONFIG_TFT_TOUCH_MIRROR_Y
#define CONFIG_TFT_TOUCH_MIRROR_Y 0
#endif
#ifndef CONFIG_TFT_TOUCH_Z_THRESHOLD
#define CONFIG_TFT_TOUCH_Z_THRESHOLD 50
#endif

#define LCD_H_RES 240
#define LCD_V_RES 320
#define FB_LINES 20

#define TFT_MOSI CONFIG_TFT_SPI_MOSI
#define TFT_SCLK CONFIG_TFT_SPI_SCLK
#define TFT_CS CONFIG_TFT_SPI_CS
#define TFT_DC CONFIG_TFT_SPI_DC
#define TFT_RST CONFIG_TFT_SPI_RST
#define TFT_MISO CONFIG_TFT_SPI_MISO
#define TFT_SPI_CLOCK_HZ CONFIG_TFT_SPI_CLOCK_HZ
#define TFT_TOUCH_SPI_CLOCK_HZ CONFIG_TFT_TOUCH_SPI_CLOCK_HZ
#define TFT_SDMMC_CLK_PIN CONFIG_TFT_SDMMC_CLK_PIN
#define TFT_SDMMC_CMD_PIN CONFIG_TFT_SDMMC_CMD_PIN
#define TFT_SDMMC_D0_PIN CONFIG_TFT_SDMMC_D0_PIN
#define TFT_SDMMC_FREQ_KHZ CONFIG_TFT_SDMMC_FREQ_KHZ
#define TFT_SPI_MODE CONFIG_TFT_SPI_MODE
#define TFT_TOUCH_SPI_MOSI CONFIG_TFT_TOUCH_SPI_MOSI
#define TFT_TOUCH_SPI_MISO CONFIG_TFT_TOUCH_SPI_MISO
#define TFT_TOUCH_SPI_SCLK CONFIG_TFT_TOUCH_SPI_SCLK
#define TFT_TOUCH_X_MIN CONFIG_TFT_TOUCH_X_MIN
#define TFT_TOUCH_X_MAX CONFIG_TFT_TOUCH_X_MAX
#define TFT_TOUCH_Y_MIN CONFIG_TFT_TOUCH_Y_MIN
#define TFT_TOUCH_Y_MAX CONFIG_TFT_TOUCH_Y_MAX
#define TFT_TOUCH_SWAP_XY CONFIG_TFT_TOUCH_SWAP_XY
#define TFT_TOUCH_MIRROR_X CONFIG_TFT_TOUCH_MIRROR_X
#define TFT_TOUCH_MIRROR_Y CONFIG_TFT_TOUCH_MIRROR_Y
#define TFT_TOUCH_Z_THRESHOLD CONFIG_TFT_TOUCH_Z_THRESHOLD
#define TFT_I2C_SDA CONFIG_TFT_I2C_SDA
#define TFT_I2C_SCL CONFIG_TFT_I2C_SCL
#define TFT_I2C_FREQ_HZ CONFIG_TFT_I2C_FREQ_HZ
#define TFT_MCP23017_ADDR CONFIG_TFT_MCP23017_ADDR
#define TFT_MCP23017_RST CONFIG_TFT_MCP23017_RST
#define TFT_ENCODER_PIN_A CONFIG_TFT_ENCODER_PIN_A
#define TFT_ENCODER_PIN_B CONFIG_TFT_ENCODER_PIN_B
#define TFT_ENCODER_PIN_SW CONFIG_TFT_ENCODER_PIN_SW
#define TFT_TOUCH_CS CONFIG_TFT_TOUCH_CS

#define TFT_TOUCH_ENABLED CONFIG_TFT_ENABLE_TOUCH
